name: CI Pipeline

on:
  push:
    branches: [ "main" ]   # Trigger when code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build project using Maven
      - name: Build with Maven
        run: mvn clean install

      # 4️⃣ Run tests (optional)
      - name: Run tests
        run: mvn test
